### ISSUE TITLE
Patch for ruma-client-api doesn't work anymore

### ISSUE THREAD

**Issue by MTRNord** [jplatte/ruma-bot#4]
Using the latest nightly `[patch.'https://github.com/ruma/ruma-client-api'.ruma-client-api]` stopped working when also using the stable future previews with the ruma-client master

**Comment by MTRNord** [comment]
Fixed in https://github.com/MTRNord/ruma-bot/tree/update-ruma and https://github.com/MTRNord/ruma-client-api/tree/request-ctors-new

Keeping it open as a tracking issue until thoose changes are merged :)

**Comment by jplatte** [comment]
Fixed.
